QuailAutomation/openhab2-addons

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ZoneHandler.java
Changed zone type from OnOff to OpenClosed. 
Added support for Zone Refresh
> Update Zones type and add zone refresh.

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AreaHandler.java
Signed-off-by: Dan Cunningham <dan@digitaldan.com>
> Alarm modes now report delayed states

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/area.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
Signed-off-by: Dan Cunningham <dan@digitaldan.com>
> Fixed typo on the spelling of auxiliary

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AreaHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ZoneHandler.java
Signed-off-by: Dan Cunningham <dan@digitaldan.com>
> Updated to use new command function

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/area.xml
- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/zone.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
Adds labels and descriptions to channels
> Digitaldan omnilink binding thing types

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AbstractOmnilinkHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AreaHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ConsoleHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/FlagHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/RoomHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ThermostatHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/UpbUnitHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ZoneHandler.java
> Use thingID() for channel binding to get the item ID.

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/ObjectPropertyRequest.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java
> Completed work on ObjectPropertyRequests

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/audio-zone.xml
- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/ObjectPropertyRequests.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AudioZoneHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ThermostatHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkHandlerFactory.java
> Audio Zone Support

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ButtonHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/FlagHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/RoomHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/ThermostatHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/UpbUnitHandler.java
Moved handlers to using channel ID
Also, fixed a defect where room state did not match channel definition.
This closes #39
> Channel ID instead of string parsing

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/ObjectPropertyRequests.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java
Fix exception in area discover.  
This fixes #55
> Discovery exception

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/unit.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/RoomHandler.java
> Changed to snake case for consistency

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AbstractOmnilinkHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
> Fix thing lookup

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/FlagHandler.java
> Fix flag switch channel

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
> Fix status updates for flags

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/aux-sensor.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/ObjectPropertyRequests.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AbstractOmnilinkHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AuxiliarySensorHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkHandlerFactory.java
This resolves the request in #98 an #97
> Auxiliary Sensor Support

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/temp-sensor.xml
fixes transposition in channel id for low temp
> Fixed channel definition.

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/humidity-sensor.xml
> Fixed pattern for low and high, fixed typo in low channel definition.

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/humidity-sensor.xml
I am on a roll w/ the typos in the thing definition.  :(
> Fixed typo in low channel definition.

- addons/binding/org.openhab.binding.isy/src/main/java/org/openhab/binding/isy/discovery/IsyRestDiscoveryService.java
New devices or version of devices. For ISY plugin
> Added new versions of devices.

- addons/binding/org.openhab.binding.omnilink/ESH-INF/thing/audio-zone.xml
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/OmnilinkBindingConstants.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/AudioZoneHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/OmnilinkBridgeHandler.java
- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/handler/audio/AudioPlayer.java
Support for audio player (pause/play/next/previous).
> Audio player support

- addons/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/discovery/OmnilinkDiscoveryService.java
Fixed duplicate discovery of temp/humidity and added area to temp/humidity sensors.
This should resolve #113
> Fix duplicate discovery of temp/humidity
